//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/distributed_computing_power_network/message/cpn_message.msg.
//

#ifndef __INET_CPN_MESSAGE_M_H
#define __INET_CPN_MESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class CprpRequestMsg;
class CprpResponseMsg;
class CprpConfirmMsg;
class TaskRequestMsg;
class TaskDataMsg;
class RespTimeoutSelfMsg;
struct computeNodeInfo;
class RespSummaryMsg;
class CgmpQueryMsg;
class CgmpReportMsg;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/networklayer/common/L3Address_m.h" // import inet.networklayer.common.L3Address


namespace inet {

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:26</tt> by opp_msgtool.
 * <pre>
 * class CprpRequestMsg extends inet::FieldsChunk
 * {
 *     // 通用字段
 *     int userId;           // 用户ID
 *     int taskId;           // 任务ID
 * 
 *     // REQ 专用字段
 *     string msgType = "CPRP_REQ";
 *     L3Address userGatewayAddress;
 * 
 *  	// 任务数据参数
 *     simtime_t generationTime;   // 任务产生的时刻
 *     int computingType; 			// 任务所需算力类型，0表示CPU，1表示GPU
 *     double requiredStorage;     // 任务所需存储空间
 *     double computingAmount;     // 任务计算量
 *     double transferAmount;      // 任务传输量
 *     simtime_t totalDelayRequirement; // 总时延要求
 *     double budget;              // 预算
 * 
 *     chunkLength = B(12 + 32); // 在构造函数中直接赋值
 * }
 * </pre>
 */
class INET_API CprpRequestMsg : public ::inet::FieldsChunk
{
  protected:
    int userId = 0;
    int taskId = 0;
    ::omnetpp::opp_string msgType = "CPRP_REQ";
    L3Address userGatewayAddress;
    ::omnetpp::simtime_t generationTime = SIMTIME_ZERO;
    int computingType = 0;
    double requiredStorage = 0;
    double computingAmount = 0;
    double transferAmount = 0;
    ::omnetpp::simtime_t totalDelayRequirement = SIMTIME_ZERO;
    double budget = 0;

  private:
    void copy(const CprpRequestMsg& other);

  protected:
    bool operator==(const CprpRequestMsg&) = delete;

  public:
    CprpRequestMsg();
    CprpRequestMsg(const CprpRequestMsg& other);
    virtual ~CprpRequestMsg();
    CprpRequestMsg& operator=(const CprpRequestMsg& other);
    virtual CprpRequestMsg *dup() const override {return new CprpRequestMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getUserId() const;
    virtual void setUserId(int userId);

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);

    virtual const L3Address& getUserGatewayAddress() const;
    virtual L3Address& getUserGatewayAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<CprpRequestMsg*>(this)->getUserGatewayAddress());}
    virtual void setUserGatewayAddress(const L3Address& userGatewayAddress);

    virtual ::omnetpp::simtime_t getGenerationTime() const;
    virtual void setGenerationTime(::omnetpp::simtime_t generationTime);

    virtual int getComputingType() const;
    virtual void setComputingType(int computingType);

    virtual double getRequiredStorage() const;
    virtual void setRequiredStorage(double requiredStorage);

    virtual double getComputingAmount() const;
    virtual void setComputingAmount(double computingAmount);

    virtual double getTransferAmount() const;
    virtual void setTransferAmount(double transferAmount);

    virtual ::omnetpp::simtime_t getTotalDelayRequirement() const;
    virtual void setTotalDelayRequirement(::omnetpp::simtime_t totalDelayRequirement);

    virtual double getBudget() const;
    virtual void setBudget(double budget);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CprpRequestMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CprpRequestMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:47</tt> by opp_msgtool.
 * <pre>
 * class CprpResponseMsg extends inet::FieldsChunk
 * {
 *     // 通用字段
 *     int userId;           // 用户ID
 *     int taskId;           // 任务ID
 * 
 *     // RESP 专用字段
 *     string msgType = "CPRP_RESP";
 * 
 *     L3Address computeNodeAddress;	// 算力节点地址 
 *     int computeNodeId;
 *     int computingType; 			// 节点算力类型，0表示CPU，1表示GPU    
 *     double computingCapacity;	// 算力
 *     double availableStorage;     // 可用存储    
 *     simtime_t sendTime;   // 发送时间戳    
 * 
 *     chunkLength = B(20 + 16); // 在构造函数中直接赋值
 * }
 * </pre>
 */
class INET_API CprpResponseMsg : public ::inet::FieldsChunk
{
  protected:
    int userId = 0;
    int taskId = 0;
    ::omnetpp::opp_string msgType = "CPRP_RESP";
    L3Address computeNodeAddress;
    int computeNodeId = 0;
    int computingType = 0;
    double computingCapacity = 0;
    double availableStorage = 0;
    ::omnetpp::simtime_t sendTime = SIMTIME_ZERO;

  private:
    void copy(const CprpResponseMsg& other);

  protected:
    bool operator==(const CprpResponseMsg&) = delete;

  public:
    CprpResponseMsg();
    CprpResponseMsg(const CprpResponseMsg& other);
    virtual ~CprpResponseMsg();
    CprpResponseMsg& operator=(const CprpResponseMsg& other);
    virtual CprpResponseMsg *dup() const override {return new CprpResponseMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getUserId() const;
    virtual void setUserId(int userId);

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);

    virtual const L3Address& getComputeNodeAddress() const;
    virtual L3Address& getComputeNodeAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<CprpResponseMsg*>(this)->getComputeNodeAddress());}
    virtual void setComputeNodeAddress(const L3Address& computeNodeAddress);

    virtual int getComputeNodeId() const;
    virtual void setComputeNodeId(int computeNodeId);

    virtual int getComputingType() const;
    virtual void setComputingType(int computingType);

    virtual double getComputingCapacity() const;
    virtual void setComputingCapacity(double computingCapacity);

    virtual double getAvailableStorage() const;
    virtual void setAvailableStorage(double availableStorage);

    virtual ::omnetpp::simtime_t getSendTime() const;
    virtual void setSendTime(::omnetpp::simtime_t sendTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CprpResponseMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CprpResponseMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:65</tt> by opp_msgtool.
 * <pre>
 * class CprpConfirmMsg extends inet::FieldsChunk
 * {
 *     // 通用字段
 *     int userId;           // 用户ID
 *     int taskId;           // 任务ID
 * 
 *     // Confirm 专用字段
 *     string msgType = "CPRP_CONFIRM";
 * 
 *     int selectedNodeId;	// 最终选定的算力节点
 * 
 * 	// 任务数据参数	
 *     simtime_t generationTime;   // 任务产生的时刻
 *     int computingType; 			// 任务所需算力类型，0表示CPU，1表示GPU
 *     double requiredStorage;     // 任务所需存储空间
 *     double computingAmount;     // 任务计算量
 *     double transferAmount;      // 任务传输量
 *     simtime_t totalDelayRequirement; // 总时延要求
 *     double budget;              // 预算 
 * 
 *     chunkLength = B(20 + 32); // 在构造函数中直接赋值
 * }
 * 
 * // ==============================================
 * // ================= 用户节点相关 =================
 * // ==============================================
 * </pre>
 */
class INET_API CprpConfirmMsg : public ::inet::FieldsChunk
{
  protected:
    int userId = 0;
    int taskId = 0;
    ::omnetpp::opp_string msgType = "CPRP_CONFIRM";
    int selectedNodeId = 0;
    ::omnetpp::simtime_t generationTime = SIMTIME_ZERO;
    int computingType = 0;
    double requiredStorage = 0;
    double computingAmount = 0;
    double transferAmount = 0;
    ::omnetpp::simtime_t totalDelayRequirement = SIMTIME_ZERO;
    double budget = 0;

  private:
    void copy(const CprpConfirmMsg& other);

  protected:
    bool operator==(const CprpConfirmMsg&) = delete;

  public:
    CprpConfirmMsg();
    CprpConfirmMsg(const CprpConfirmMsg& other);
    virtual ~CprpConfirmMsg();
    CprpConfirmMsg& operator=(const CprpConfirmMsg& other);
    virtual CprpConfirmMsg *dup() const override {return new CprpConfirmMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getUserId() const;
    virtual void setUserId(int userId);

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);

    virtual int getSelectedNodeId() const;
    virtual void setSelectedNodeId(int selectedNodeId);

    virtual ::omnetpp::simtime_t getGenerationTime() const;
    virtual void setGenerationTime(::omnetpp::simtime_t generationTime);

    virtual int getComputingType() const;
    virtual void setComputingType(int computingType);

    virtual double getRequiredStorage() const;
    virtual void setRequiredStorage(double requiredStorage);

    virtual double getComputingAmount() const;
    virtual void setComputingAmount(double computingAmount);

    virtual double getTransferAmount() const;
    virtual void setTransferAmount(double transferAmount);

    virtual ::omnetpp::simtime_t getTotalDelayRequirement() const;
    virtual void setTotalDelayRequirement(::omnetpp::simtime_t totalDelayRequirement);

    virtual double getBudget() const;
    virtual void setBudget(double budget);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CprpConfirmMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CprpConfirmMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:91</tt> by opp_msgtool.
 * <pre>
 * class TaskRequestMsg extends inet::FieldsChunk
 * {
 *     // 通用字段
 *     int userId;           // 用户ID
 *     int taskId;           // 任务ID
 * 
 *     string msgType = "TaskRequestMsg";
 * 
 *  	// 任务数据参数
 *     simtime_t generationTime;   // 任务产生的时刻
 *     int computingType; 			// 任务所需算力类型，0表示CPU，1表示GPU
 *     double requiredStorage;     // 任务所需存储空间
 *     double computingAmount;     // 任务计算量
 *     double transferAmount;      // 任务传输量
 *     simtime_t totalDelayRequirement; // 总时延要求
 *     double budget;              // 预算
 * 
 *     chunkLength = B(12 + 32); // 在构造函数中直接赋值
 * }
 * 
 * // ==============================================
 * // ================= 用户网关相关 =================
 * // ==============================================
 * </pre>
 */
class INET_API TaskRequestMsg : public ::inet::FieldsChunk
{
  protected:
    int userId = 0;
    int taskId = 0;
    ::omnetpp::opp_string msgType = "TaskRequestMsg";
    ::omnetpp::simtime_t generationTime = SIMTIME_ZERO;
    int computingType = 0;
    double requiredStorage = 0;
    double computingAmount = 0;
    double transferAmount = 0;
    ::omnetpp::simtime_t totalDelayRequirement = SIMTIME_ZERO;
    double budget = 0;

  private:
    void copy(const TaskRequestMsg& other);

  protected:
    bool operator==(const TaskRequestMsg&) = delete;

  public:
    TaskRequestMsg();
    TaskRequestMsg(const TaskRequestMsg& other);
    virtual ~TaskRequestMsg();
    TaskRequestMsg& operator=(const TaskRequestMsg& other);
    virtual TaskRequestMsg *dup() const override {return new TaskRequestMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getUserId() const;
    virtual void setUserId(int userId);

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);

    virtual ::omnetpp::simtime_t getGenerationTime() const;
    virtual void setGenerationTime(::omnetpp::simtime_t generationTime);

    virtual int getComputingType() const;
    virtual void setComputingType(int computingType);

    virtual double getRequiredStorage() const;
    virtual void setRequiredStorage(double requiredStorage);

    virtual double getComputingAmount() const;
    virtual void setComputingAmount(double computingAmount);

    virtual double getTransferAmount() const;
    virtual void setTransferAmount(double transferAmount);

    virtual ::omnetpp::simtime_t getTotalDelayRequirement() const;
    virtual void setTotalDelayRequirement(::omnetpp::simtime_t totalDelayRequirement);

    virtual double getBudget() const;
    virtual void setBudget(double budget);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskRequestMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskRequestMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:115</tt> by opp_msgtool.
 * <pre>
 * // 任务数据消息
 * class TaskDataMsg extends inet::FieldsChunk
 * {
 *     // 通用字段
 *     int userId;           // 用户ID
 *     int taskId;           // 任务ID
 * 
 *     string msgType = "TaskDataMsg";
 *     L3Address userNodeAddress;
 * 
 * 	// 任务数据参数	
 *     simtime_t generationTime;   // 任务产生的时刻
 *     int computingType; 			// 任务所需算力类型，0表示CPU，1表示GPU
 *     double requiredStorage;     // 任务所需存储空间
 *     double computingAmount;     // 任务计算量
 *     double transferAmount;      // 任务传输量
 *     simtime_t totalDelayRequirement; // 总时延要求
 *     double budget;              // 预算 
 * 
 *     chunkLength = B(12 + 32); // 在构造函数中直接赋值
 * }
 * </pre>
 */
class INET_API TaskDataMsg : public ::inet::FieldsChunk
{
  protected:
    int userId = 0;
    int taskId = 0;
    ::omnetpp::opp_string msgType = "TaskDataMsg";
    L3Address userNodeAddress;
    ::omnetpp::simtime_t generationTime = SIMTIME_ZERO;
    int computingType = 0;
    double requiredStorage = 0;
    double computingAmount = 0;
    double transferAmount = 0;
    ::omnetpp::simtime_t totalDelayRequirement = SIMTIME_ZERO;
    double budget = 0;

  private:
    void copy(const TaskDataMsg& other);

  protected:
    bool operator==(const TaskDataMsg&) = delete;

  public:
    TaskDataMsg();
    TaskDataMsg(const TaskDataMsg& other);
    virtual ~TaskDataMsg();
    TaskDataMsg& operator=(const TaskDataMsg& other);
    virtual TaskDataMsg *dup() const override {return new TaskDataMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getUserId() const;
    virtual void setUserId(int userId);

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);

    virtual const L3Address& getUserNodeAddress() const;
    virtual L3Address& getUserNodeAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<TaskDataMsg*>(this)->getUserNodeAddress());}
    virtual void setUserNodeAddress(const L3Address& userNodeAddress);

    virtual ::omnetpp::simtime_t getGenerationTime() const;
    virtual void setGenerationTime(::omnetpp::simtime_t generationTime);

    virtual int getComputingType() const;
    virtual void setComputingType(int computingType);

    virtual double getRequiredStorage() const;
    virtual void setRequiredStorage(double requiredStorage);

    virtual double getComputingAmount() const;
    virtual void setComputingAmount(double computingAmount);

    virtual double getTransferAmount() const;
    virtual void setTransferAmount(double transferAmount);

    virtual ::omnetpp::simtime_t getTotalDelayRequirement() const;
    virtual void setTotalDelayRequirement(::omnetpp::simtime_t totalDelayRequirement);

    virtual double getBudget() const;
    virtual void setBudget(double budget);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskDataMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskDataMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:136</tt> by opp_msgtool.
 * <pre>
 * // 算力应答超时自消息
 * class RespTimeoutSelfMsg extends cMessage
 * {
 *     string msgType = "RespTimeoutSelfMsg";
 *     int userId;
 *     int taskId;
 * }
 * </pre>
 */
class INET_API RespTimeoutSelfMsg : public ::omnetpp::cMessage
{
  protected:
    ::omnetpp::opp_string msgType = "RespTimeoutSelfMsg";
    int userId = 0;
    int taskId = 0;

  private:
    void copy(const RespTimeoutSelfMsg& other);

  protected:
    bool operator==(const RespTimeoutSelfMsg&) = delete;

  public:
    RespTimeoutSelfMsg(const char *name=nullptr);
    RespTimeoutSelfMsg(const RespTimeoutSelfMsg& other);
    virtual ~RespTimeoutSelfMsg();
    RespTimeoutSelfMsg& operator=(const RespTimeoutSelfMsg& other);
    virtual RespTimeoutSelfMsg *dup() const override {return new RespTimeoutSelfMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);

    virtual int getUserId() const;
    virtual void setUserId(int userId);

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RespTimeoutSelfMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RespTimeoutSelfMsg& obj) {obj.parsimUnpack(b);}

/**
 * Struct generated from inet/distributed_computing_power_network/message/cpn_message.msg:143 by opp_msgtool.
 */
struct INET_API computeNodeInfo
{
    computeNodeInfo();
    L3Address computeNodeAddress;
    int computeNodeId = 0;
    int computingType = 0;
    double computingCapacity = 0;
    double availableStorage = 0;
    ::omnetpp::simtime_t sendTime = SIMTIME_ZERO;
};

// helpers for local use
void INET_API __doPacking(omnetpp::cCommBuffer *b, const computeNodeInfo& a);
void INET_API __doUnpacking(omnetpp::cCommBuffer *b, computeNodeInfo& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const computeNodeInfo& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, computeNodeInfo& obj) { __doUnpacking(b, obj); }

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:152</tt> by opp_msgtool.
 * <pre>
 * class RespSummaryMsg extends inet::FieldsChunk
 * {
 *     // 通用字段
 *     int userId;           // 用户ID
 *     int taskId;           // 任务ID
 * 
 *     string msgType = "RespSummaryMsg";
 * 
 *     computeNodeInfo nodeInfo[];
 * 
 *     chunkLength = B(12 + 32); // 在构造函数中直接赋值
 * }
 * 
 * // ==============================================
 * // ================== CGMP 协议 ==================
 * // ==============================================
 * </pre>
 */
class INET_API RespSummaryMsg : public ::inet::FieldsChunk
{
  protected:
    int userId = 0;
    int taskId = 0;
    ::omnetpp::opp_string msgType = "RespSummaryMsg";
    computeNodeInfo *nodeInfo = nullptr;
    size_t nodeInfo_arraysize = 0;

  private:
    void copy(const RespSummaryMsg& other);

  protected:
    bool operator==(const RespSummaryMsg&) = delete;

  public:
    RespSummaryMsg();
    RespSummaryMsg(const RespSummaryMsg& other);
    virtual ~RespSummaryMsg();
    RespSummaryMsg& operator=(const RespSummaryMsg& other);
    virtual RespSummaryMsg *dup() const override {return new RespSummaryMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getUserId() const;
    virtual void setUserId(int userId);

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);

    virtual void setNodeInfoArraySize(size_t size);
    virtual size_t getNodeInfoArraySize() const;
    virtual const computeNodeInfo& getNodeInfo(size_t k) const;
    virtual computeNodeInfo& getNodeInfoForUpdate(size_t k) { handleChange();return const_cast<computeNodeInfo&>(const_cast<RespSummaryMsg*>(this)->getNodeInfo(k));}
    virtual void setNodeInfo(size_t k, const computeNodeInfo& nodeInfo);
    virtual void insertNodeInfo(size_t k, const computeNodeInfo& nodeInfo);
    [[deprecated]] void insertNodeInfo(const computeNodeInfo& nodeInfo) {appendNodeInfo(nodeInfo);}
    virtual void appendNodeInfo(const computeNodeInfo& nodeInfo);
    virtual void eraseNodeInfo(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RespSummaryMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RespSummaryMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:168</tt> by opp_msgtool.
 * <pre>
 * class CgmpQueryMsg extends inet::FieldsChunk
 * {
 *     string msgType = "CGMP_Query";
 * 
 *     chunkLength = B(1); // 在构造函数中直接赋值	    
 * }
 * </pre>
 */
class INET_API CgmpQueryMsg : public ::inet::FieldsChunk
{
  protected:
    ::omnetpp::opp_string msgType = "CGMP_Query";

  private:
    void copy(const CgmpQueryMsg& other);

  protected:
    bool operator==(const CgmpQueryMsg&) = delete;

  public:
    CgmpQueryMsg();
    CgmpQueryMsg(const CgmpQueryMsg& other);
    virtual ~CgmpQueryMsg();
    CgmpQueryMsg& operator=(const CgmpQueryMsg& other);
    virtual CgmpQueryMsg *dup() const override {return new CgmpQueryMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CgmpQueryMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CgmpQueryMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:174</tt> by opp_msgtool.
 * <pre>
 * class CgmpReportMsg extends inet::FieldsChunk
 * {
 *     string msgType = "CGMP_Report";
 * 
 *     int computeNodeId;
 *     int computingType; 			// 节点算力类型，0表示CPU，1表示GPU    
 *     L3Address computeNodeAddress;
 *     double computingCapacity;	// 算力
 *     double availableStorage;     // 可用存储    
 *     simtime_t sendTime;   // 发送时间戳    
 * 
 *     chunkLength = B(8 + 16); // 在构造函数中直接赋值	    
 * }
 * </pre>
 */
class INET_API CgmpReportMsg : public ::inet::FieldsChunk
{
  protected:
    ::omnetpp::opp_string msgType = "CGMP_Report";
    int computeNodeId = 0;
    int computingType = 0;
    L3Address computeNodeAddress;
    double computingCapacity = 0;
    double availableStorage = 0;
    ::omnetpp::simtime_t sendTime = SIMTIME_ZERO;

  private:
    void copy(const CgmpReportMsg& other);

  protected:
    bool operator==(const CgmpReportMsg&) = delete;

  public:
    CgmpReportMsg();
    CgmpReportMsg(const CgmpReportMsg& other);
    virtual ~CgmpReportMsg();
    CgmpReportMsg& operator=(const CgmpReportMsg& other);
    virtual CgmpReportMsg *dup() const override {return new CgmpReportMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);

    virtual int getComputeNodeId() const;
    virtual void setComputeNodeId(int computeNodeId);

    virtual int getComputingType() const;
    virtual void setComputingType(int computingType);

    virtual const L3Address& getComputeNodeAddress() const;
    virtual L3Address& getComputeNodeAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<CgmpReportMsg*>(this)->getComputeNodeAddress());}
    virtual void setComputeNodeAddress(const L3Address& computeNodeAddress);

    virtual double getComputingCapacity() const;
    virtual void setComputingCapacity(double computingCapacity);

    virtual double getAvailableStorage() const;
    virtual void setAvailableStorage(double availableStorage);

    virtual ::omnetpp::simtime_t getSendTime() const;
    virtual void setSendTime(::omnetpp::simtime_t sendTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CgmpReportMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CgmpReportMsg& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::CprpRequestMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::CprpRequestMsg*>(ptr.get<cObject>()); }
template<> inline inet::CprpResponseMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::CprpResponseMsg*>(ptr.get<cObject>()); }
template<> inline inet::CprpConfirmMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::CprpConfirmMsg*>(ptr.get<cObject>()); }
template<> inline inet::TaskRequestMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::TaskRequestMsg*>(ptr.get<cObject>()); }
template<> inline inet::TaskDataMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::TaskDataMsg*>(ptr.get<cObject>()); }
template<> inline inet::RespTimeoutSelfMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::RespTimeoutSelfMsg*>(ptr.get<cObject>()); }
inline any_ptr toAnyPtr(const inet::computeNodeInfo *p) {return any_ptr(p);}
template<> inline inet::computeNodeInfo *fromAnyPtr(any_ptr ptr) { return ptr.get<inet::computeNodeInfo>(); }
template<> inline inet::RespSummaryMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::RespSummaryMsg*>(ptr.get<cObject>()); }
template<> inline inet::CgmpQueryMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::CgmpQueryMsg*>(ptr.get<cObject>()); }
template<> inline inet::CgmpReportMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::CgmpReportMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_CPN_MESSAGE_M_H

