//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/distributed_computing_power_network/message/cpn_message.msg.
//

#ifndef __INET_CPN_MESSAGE_M_H
#define __INET_CPN_MESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class CprpRequestMsg;
class CprpResponseMsg;
class CprpConfirmMsg;
class CancelMsg;
class TaskRequestMsg;
class TaskDataMsg;
class RespTimeoutSelfMsg;
struct computeNodeInfo;
struct routeInfo;
struct computeCandidateInfo;
class RespSummaryMsg;
class CgmpQueryMsg;
struct cgmpTaskState;
class CgmpReportMsg;
class TaskCompletionMsg;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/networklayer/common/L3Address_m.h" // import inet.networklayer.common.L3Address


namespace inet {

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:26</tt> by opp_msgtool.
 * <pre>
 * class CprpRequestMsg extends inet::FieldsChunk
 * {
 *     // 通用字段
 *     int userId;           // 用户ID
 *     int taskId;           // 任务ID
 * 
 *     // REQ 专用字段
 *     string msgType = "CPRP_REQ";
 *     L3Address userGatewayAddress;
 *     L3Address userNodeAddress;       // 产生任务的用户节点地址
 *     int userNodePort;                // 用户节点端口号
 *     simtime_t userAccessRtt;         // 用户节点到用户网关的估计往返网络时延
 *     simtime_t userGatewayForwardTime; // 用户网关转发 CPRP_REQ 的时间戳
 * 
 *     // 任务数据参数
 *     simtime_t generationTime;   // 任务产生的时刻
 *     int computingType; 			// 任务所需算力类型，0表示CPU，1表示GPU
 *     double requiredStorage;     // 任务所需存储空间(MB)
 *     double computingAmount;     // 任务计算量(FLOPs)
 *     double transferAmount;      // 任务数据量(MB)
 *     simtime_t totalDelayRequirement; // 时延忍耐值(sec)
 *     double budget;              // 预算
 *     double userMaxBandwidth;    // 传输带宽(Mbps)
 * 
 *     chunkLength = B(32 + 56); // 在构造函数中直接赋值
 * }
 * </pre>
 */
class INET_API CprpRequestMsg : public ::inet::FieldsChunk
{
  protected:
    int userId = 0;
    int taskId = 0;
    ::omnetpp::opp_string msgType = "CPRP_REQ";
    L3Address userGatewayAddress;
    L3Address userNodeAddress;
    int userNodePort = 0;
    ::omnetpp::simtime_t userAccessRtt = SIMTIME_ZERO;
    ::omnetpp::simtime_t userGatewayForwardTime = SIMTIME_ZERO;
    ::omnetpp::simtime_t generationTime = SIMTIME_ZERO;
    int computingType = 0;
    double requiredStorage = 0;
    double computingAmount = 0;
    double transferAmount = 0;
    ::omnetpp::simtime_t totalDelayRequirement = SIMTIME_ZERO;
    double budget = 0;
    double userMaxBandwidth = 0;

  private:
    void copy(const CprpRequestMsg& other);

  protected:
    bool operator==(const CprpRequestMsg&) = delete;

  public:
    CprpRequestMsg();
    CprpRequestMsg(const CprpRequestMsg& other);
    virtual ~CprpRequestMsg();
    CprpRequestMsg& operator=(const CprpRequestMsg& other);
    virtual CprpRequestMsg *dup() const override {return new CprpRequestMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getUserId() const;
    virtual void setUserId(int userId);

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);

    virtual const L3Address& getUserGatewayAddress() const;
    virtual L3Address& getUserGatewayAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<CprpRequestMsg*>(this)->getUserGatewayAddress());}
    virtual void setUserGatewayAddress(const L3Address& userGatewayAddress);

    virtual const L3Address& getUserNodeAddress() const;
    virtual L3Address& getUserNodeAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<CprpRequestMsg*>(this)->getUserNodeAddress());}
    virtual void setUserNodeAddress(const L3Address& userNodeAddress);

    virtual int getUserNodePort() const;
    virtual void setUserNodePort(int userNodePort);

    virtual ::omnetpp::simtime_t getUserAccessRtt() const;
    virtual void setUserAccessRtt(::omnetpp::simtime_t userAccessRtt);

    virtual ::omnetpp::simtime_t getUserGatewayForwardTime() const;
    virtual void setUserGatewayForwardTime(::omnetpp::simtime_t userGatewayForwardTime);

    virtual ::omnetpp::simtime_t getGenerationTime() const;
    virtual void setGenerationTime(::omnetpp::simtime_t generationTime);

    virtual int getComputingType() const;
    virtual void setComputingType(int computingType);

    virtual double getRequiredStorage() const;
    virtual void setRequiredStorage(double requiredStorage);

    virtual double getComputingAmount() const;
    virtual void setComputingAmount(double computingAmount);

    virtual double getTransferAmount() const;
    virtual void setTransferAmount(double transferAmount);

    virtual ::omnetpp::simtime_t getTotalDelayRequirement() const;
    virtual void setTotalDelayRequirement(::omnetpp::simtime_t totalDelayRequirement);

    virtual double getBudget() const;
    virtual void setBudget(double budget);

    virtual double getUserMaxBandwidth() const;
    virtual void setUserMaxBandwidth(double userMaxBandwidth);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CprpRequestMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CprpRequestMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:52</tt> by opp_msgtool.
 * <pre>
 * class CprpResponseMsg extends inet::FieldsChunk
 * {
 *     // 通用字段
 *     int userId;           // 用户ID
 *     int taskId;           // 任务ID
 * 
 *     // RESP 专用字段
 *     string msgType = "CPRP_RESP";
 * 
 *     L3Address computeNodeAddress;	// 算力节点地址 
 *     int computeNodeId;
 *     int computeNodePort;			// 算力节点端口号
 *     int computingType; 			// 节点算力类型，0表示CPU，1表示GPU    
 *     double computingCapacity;	// 计算能力(FLOPs/s)
 *     double availableStorage;     // 可用存储(MB)
 *     double maxNetworkBandwidth;  // 最大可用网络带宽(Mbps)
 *     simtime_t sendTime;   // 发送时间戳
 * 
 *     // 资源预留参数
 *     double requiredBandwidth;       // 网络层预留带宽(bps)
 *     simtime_t maxDelayTolerance;    // 最大时延忍耐值
 *     double computeCost;             // 使用成本(￥/s)
 * 
 *     // 时延信息
 *     simtime_t accumulatedDelay;     // 算力网关计算的总时延
 * 
 *     // 路由选择相关字段
 *     simtime_t lastHopSendTime;      // 上一跳发送时间戳
 *     L3Address lastHopAddress;       // 上一跳IP地址
 * 
 *     chunkLength = B(32 + 72);
 * }
 * </pre>
 */
class INET_API CprpResponseMsg : public ::inet::FieldsChunk
{
  protected:
    int userId = 0;
    int taskId = 0;
    ::omnetpp::opp_string msgType = "CPRP_RESP";
    L3Address computeNodeAddress;
    int computeNodeId = 0;
    int computeNodePort = 0;
    int computingType = 0;
    double computingCapacity = 0;
    double availableStorage = 0;
    double maxNetworkBandwidth = 0;
    ::omnetpp::simtime_t sendTime = SIMTIME_ZERO;
    double requiredBandwidth = 0;
    ::omnetpp::simtime_t maxDelayTolerance = SIMTIME_ZERO;
    double computeCost = 0;
    ::omnetpp::simtime_t accumulatedDelay = SIMTIME_ZERO;
    ::omnetpp::simtime_t lastHopSendTime = SIMTIME_ZERO;
    L3Address lastHopAddress;

  private:
    void copy(const CprpResponseMsg& other);

  protected:
    bool operator==(const CprpResponseMsg&) = delete;

  public:
    CprpResponseMsg();
    CprpResponseMsg(const CprpResponseMsg& other);
    virtual ~CprpResponseMsg();
    CprpResponseMsg& operator=(const CprpResponseMsg& other);
    virtual CprpResponseMsg *dup() const override {return new CprpResponseMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getUserId() const;
    virtual void setUserId(int userId);

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);

    virtual const L3Address& getComputeNodeAddress() const;
    virtual L3Address& getComputeNodeAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<CprpResponseMsg*>(this)->getComputeNodeAddress());}
    virtual void setComputeNodeAddress(const L3Address& computeNodeAddress);

    virtual int getComputeNodeId() const;
    virtual void setComputeNodeId(int computeNodeId);

    virtual int getComputeNodePort() const;
    virtual void setComputeNodePort(int computeNodePort);

    virtual int getComputingType() const;
    virtual void setComputingType(int computingType);

    virtual double getComputingCapacity() const;
    virtual void setComputingCapacity(double computingCapacity);

    virtual double getAvailableStorage() const;
    virtual void setAvailableStorage(double availableStorage);

    virtual double getMaxNetworkBandwidth() const;
    virtual void setMaxNetworkBandwidth(double maxNetworkBandwidth);

    virtual ::omnetpp::simtime_t getSendTime() const;
    virtual void setSendTime(::omnetpp::simtime_t sendTime);

    virtual double getRequiredBandwidth() const;
    virtual void setRequiredBandwidth(double requiredBandwidth);

    virtual ::omnetpp::simtime_t getMaxDelayTolerance() const;
    virtual void setMaxDelayTolerance(::omnetpp::simtime_t maxDelayTolerance);

    virtual double getComputeCost() const;
    virtual void setComputeCost(double computeCost);

    virtual ::omnetpp::simtime_t getAccumulatedDelay() const;
    virtual void setAccumulatedDelay(::omnetpp::simtime_t accumulatedDelay);

    virtual ::omnetpp::simtime_t getLastHopSendTime() const;
    virtual void setLastHopSendTime(::omnetpp::simtime_t lastHopSendTime);

    virtual const L3Address& getLastHopAddress() const;
    virtual L3Address& getLastHopAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<CprpResponseMsg*>(this)->getLastHopAddress());}
    virtual void setLastHopAddress(const L3Address& lastHopAddress);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CprpResponseMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CprpResponseMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:84</tt> by opp_msgtool.
 * <pre>
 * class CprpConfirmMsg extends inet::FieldsChunk
 * {
 *     // 通用字段
 *     int userId;           // 用户ID
 *     int taskId;           // 任务ID
 * 
 *     // Confirm 专用字段
 *     string msgType = "CPRP_CONFIRM";
 * 
 *     int selectedNodeId;	// 最终选定的算力节点
 *     L3Address selectedNodeAddress;  // 选定算力节点IP
 *     int selectedNodePort;           // 选定算力节点端口
 *     int selectedPathIndex = 0;      // 用户选定的路径索引
 * 
 *     chunkLength = B(28);
 * }
 * </pre>
 */
class INET_API CprpConfirmMsg : public ::inet::FieldsChunk
{
  protected:
    int userId = 0;
    int taskId = 0;
    ::omnetpp::opp_string msgType = "CPRP_CONFIRM";
    int selectedNodeId = 0;
    L3Address selectedNodeAddress;
    int selectedNodePort = 0;
    int selectedPathIndex = 0;

  private:
    void copy(const CprpConfirmMsg& other);

  protected:
    bool operator==(const CprpConfirmMsg&) = delete;

  public:
    CprpConfirmMsg();
    CprpConfirmMsg(const CprpConfirmMsg& other);
    virtual ~CprpConfirmMsg();
    CprpConfirmMsg& operator=(const CprpConfirmMsg& other);
    virtual CprpConfirmMsg *dup() const override {return new CprpConfirmMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getUserId() const;
    virtual void setUserId(int userId);

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);

    virtual int getSelectedNodeId() const;
    virtual void setSelectedNodeId(int selectedNodeId);

    virtual const L3Address& getSelectedNodeAddress() const;
    virtual L3Address& getSelectedNodeAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<CprpConfirmMsg*>(this)->getSelectedNodeAddress());}
    virtual void setSelectedNodeAddress(const L3Address& selectedNodeAddress);

    virtual int getSelectedNodePort() const;
    virtual void setSelectedNodePort(int selectedNodePort);

    virtual int getSelectedPathIndex() const;
    virtual void setSelectedPathIndex(int selectedPathIndex);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CprpConfirmMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CprpConfirmMsg& obj) {obj.parsimUnpack(b);}

/**
 * Enum generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:100</tt> by opp_msgtool.
 * <pre>
 * enum CancelSenderType
 * {
 *     SENDER_USER_GW = 0;
 *     SENDER_COMPUTE_GW = 1;
 *     SENDER_COMPUTE_ROUTER = 2;
 * }
 * </pre>
 */
enum CancelSenderType {
    SENDER_USER_GW = 0,
    SENDER_COMPUTE_GW = 1,
    SENDER_COMPUTE_ROUTER = 2
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CancelSenderType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CancelSenderType& e) { int n; b->unpack(n); e = static_cast<CancelSenderType>(n); }

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:106</tt> by opp_msgtool.
 * <pre>
 * class CancelMsg extends inet::FieldsChunk
 * {
 *     int userId;                       // 用户ID
 *     int taskId;                       // 任务ID
 *     L3Address computeNodeAddress;     // 算力节点IP
 *     int computeNodePort;              // 算力节点端口
 *     int senderType;                   // 发送方类型 (CancelSenderType)
 * 
 *     string msgType = "CPRP_CANCEL";
 *     chunkLength = B(20);
 * }
 * 
 * // ==============================================
 * // ================= 用户节点相关 =================
 * // ==============================================
 * </pre>
 */
class INET_API CancelMsg : public ::inet::FieldsChunk
{
  protected:
    int userId = 0;
    int taskId = 0;
    L3Address computeNodeAddress;
    int computeNodePort = 0;
    int senderType = 0;
    ::omnetpp::opp_string msgType = "CPRP_CANCEL";

  private:
    void copy(const CancelMsg& other);

  protected:
    bool operator==(const CancelMsg&) = delete;

  public:
    CancelMsg();
    CancelMsg(const CancelMsg& other);
    virtual ~CancelMsg();
    CancelMsg& operator=(const CancelMsg& other);
    virtual CancelMsg *dup() const override {return new CancelMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getUserId() const;
    virtual void setUserId(int userId);

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual const L3Address& getComputeNodeAddress() const;
    virtual L3Address& getComputeNodeAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<CancelMsg*>(this)->getComputeNodeAddress());}
    virtual void setComputeNodeAddress(const L3Address& computeNodeAddress);

    virtual int getComputeNodePort() const;
    virtual void setComputeNodePort(int computeNodePort);

    virtual int getSenderType() const;
    virtual void setSenderType(int senderType);

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CancelMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CancelMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:121</tt> by opp_msgtool.
 * <pre>
 * class TaskRequestMsg extends inet::FieldsChunk
 * {
 *     // 通用字段
 *     int userId;           // 用户ID
 *     int taskId;           // 任务ID
 * 
 *     string msgType = "TaskRequestMsg";
 * 
 *  	// 任务数据参数
 *     simtime_t generationTime;   // 任务产生的时刻
 *     int computingType; 			// 任务所需算力类型，0表示CPU，1表示GPU
 *     double requiredStorage;     // 任务所需存储空间(MB)
 *     double computingAmount;     // 任务计算量(FLOPs)
 *     double transferAmount;      // 任务数据量(MB)
 *     simtime_t totalDelayRequirement; // 时延忍耐值(sec)
 *     double budget;              // 预算
 *     double userMaxBandwidth;    // 传输带宽(Mbps)
 * 
 *     chunkLength = B(12 + 40); // 在构造函数中直接赋值
 * }
 * 
 * // ==============================================
 * // ================= 用户网关相关 =================
 * // ==============================================
 * </pre>
 */
class INET_API TaskRequestMsg : public ::inet::FieldsChunk
{
  protected:
    int userId = 0;
    int taskId = 0;
    ::omnetpp::opp_string msgType = "TaskRequestMsg";
    ::omnetpp::simtime_t generationTime = SIMTIME_ZERO;
    int computingType = 0;
    double requiredStorage = 0;
    double computingAmount = 0;
    double transferAmount = 0;
    ::omnetpp::simtime_t totalDelayRequirement = SIMTIME_ZERO;
    double budget = 0;
    double userMaxBandwidth = 0;

  private:
    void copy(const TaskRequestMsg& other);

  protected:
    bool operator==(const TaskRequestMsg&) = delete;

  public:
    TaskRequestMsg();
    TaskRequestMsg(const TaskRequestMsg& other);
    virtual ~TaskRequestMsg();
    TaskRequestMsg& operator=(const TaskRequestMsg& other);
    virtual TaskRequestMsg *dup() const override {return new TaskRequestMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getUserId() const;
    virtual void setUserId(int userId);

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);

    virtual ::omnetpp::simtime_t getGenerationTime() const;
    virtual void setGenerationTime(::omnetpp::simtime_t generationTime);

    virtual int getComputingType() const;
    virtual void setComputingType(int computingType);

    virtual double getRequiredStorage() const;
    virtual void setRequiredStorage(double requiredStorage);

    virtual double getComputingAmount() const;
    virtual void setComputingAmount(double computingAmount);

    virtual double getTransferAmount() const;
    virtual void setTransferAmount(double transferAmount);

    virtual ::omnetpp::simtime_t getTotalDelayRequirement() const;
    virtual void setTotalDelayRequirement(::omnetpp::simtime_t totalDelayRequirement);

    virtual double getBudget() const;
    virtual void setBudget(double budget);

    virtual double getUserMaxBandwidth() const;
    virtual void setUserMaxBandwidth(double userMaxBandwidth);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskRequestMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskRequestMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:146</tt> by opp_msgtool.
 * <pre>
 * // 任务数据消息
 * class TaskDataMsg extends inet::FieldsChunk
 * {
 *     // 通用字段
 *     int userId;           // 用户ID
 *     int taskId;           // 任务ID
 * 
 *     string msgType = "TaskDataMsg";
 *     L3Address userNodeAddress;
 *     int userNodePort;                // 用户节点端口号
 * 
 * 	// 任务数据参数	
 *     simtime_t generationTime;   // 任务产生的时刻
 *     int computingType; 			// 任务所需算力类型，0表示CPU，1表示GPU
 *     double requiredStorage;     // 任务所需存储空间(MB)
 *     double computingAmount;     // 任务计算量(FLOPs)
 *     double transferAmount;      // 任务数据量(MB)
 *     simtime_t totalDelayRequirement; // 时延忍耐值(sec)
 *     double budget;              // 预算
 *     double userMaxBandwidth;    // 传输带宽(Mbps)
 *     int priority = 5;           // DSCP优先级，默认EF(5)
 * 
 *     chunkLength = B(20 + 40); // 在构造函数中直接赋值
 * }
 * </pre>
 */
class INET_API TaskDataMsg : public ::inet::FieldsChunk
{
  protected:
    int userId = 0;
    int taskId = 0;
    ::omnetpp::opp_string msgType = "TaskDataMsg";
    L3Address userNodeAddress;
    int userNodePort = 0;
    ::omnetpp::simtime_t generationTime = SIMTIME_ZERO;
    int computingType = 0;
    double requiredStorage = 0;
    double computingAmount = 0;
    double transferAmount = 0;
    ::omnetpp::simtime_t totalDelayRequirement = SIMTIME_ZERO;
    double budget = 0;
    double userMaxBandwidth = 0;
    int priority = 5;

  private:
    void copy(const TaskDataMsg& other);

  protected:
    bool operator==(const TaskDataMsg&) = delete;

  public:
    TaskDataMsg();
    TaskDataMsg(const TaskDataMsg& other);
    virtual ~TaskDataMsg();
    TaskDataMsg& operator=(const TaskDataMsg& other);
    virtual TaskDataMsg *dup() const override {return new TaskDataMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getUserId() const;
    virtual void setUserId(int userId);

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);

    virtual const L3Address& getUserNodeAddress() const;
    virtual L3Address& getUserNodeAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<TaskDataMsg*>(this)->getUserNodeAddress());}
    virtual void setUserNodeAddress(const L3Address& userNodeAddress);

    virtual int getUserNodePort() const;
    virtual void setUserNodePort(int userNodePort);

    virtual ::omnetpp::simtime_t getGenerationTime() const;
    virtual void setGenerationTime(::omnetpp::simtime_t generationTime);

    virtual int getComputingType() const;
    virtual void setComputingType(int computingType);

    virtual double getRequiredStorage() const;
    virtual void setRequiredStorage(double requiredStorage);

    virtual double getComputingAmount() const;
    virtual void setComputingAmount(double computingAmount);

    virtual double getTransferAmount() const;
    virtual void setTransferAmount(double transferAmount);

    virtual ::omnetpp::simtime_t getTotalDelayRequirement() const;
    virtual void setTotalDelayRequirement(::omnetpp::simtime_t totalDelayRequirement);

    virtual double getBudget() const;
    virtual void setBudget(double budget);

    virtual double getUserMaxBandwidth() const;
    virtual void setUserMaxBandwidth(double userMaxBandwidth);

    virtual int getPriority() const;
    virtual void setPriority(int priority);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskDataMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskDataMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:170</tt> by opp_msgtool.
 * <pre>
 * // 算力应答超时自消息
 * class RespTimeoutSelfMsg extends cMessage
 * {
 *     string msgType = "RespTimeoutSelfMsg";
 *     int userId;
 *     int taskId;
 * }
 * </pre>
 */
class INET_API RespTimeoutSelfMsg : public ::omnetpp::cMessage
{
  protected:
    ::omnetpp::opp_string msgType = "RespTimeoutSelfMsg";
    int userId = 0;
    int taskId = 0;

  private:
    void copy(const RespTimeoutSelfMsg& other);

  protected:
    bool operator==(const RespTimeoutSelfMsg&) = delete;

  public:
    RespTimeoutSelfMsg(const char *name=nullptr);
    RespTimeoutSelfMsg(const RespTimeoutSelfMsg& other);
    virtual ~RespTimeoutSelfMsg();
    RespTimeoutSelfMsg& operator=(const RespTimeoutSelfMsg& other);
    virtual RespTimeoutSelfMsg *dup() const override {return new RespTimeoutSelfMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);

    virtual int getUserId() const;
    virtual void setUserId(int userId);

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RespTimeoutSelfMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RespTimeoutSelfMsg& obj) {obj.parsimUnpack(b);}

/**
 * Struct generated from inet/distributed_computing_power_network/message/cpn_message.msg:177 by opp_msgtool.
 */
struct INET_API computeNodeInfo
{
    computeNodeInfo();
    L3Address computeNodeAddress;
    int computeNodeId = 0;
    int computeNodePort = 0;
    int computingType = 0;
    double computingCapacity = 0;
    double availableStorage = 0;
    double maxNetworkBandwidth = 0;
    double computeCost = 0;
    ::omnetpp::simtime_t sendTime = SIMTIME_ZERO;
};

// helpers for local use
void INET_API __doPacking(omnetpp::cCommBuffer *b, const computeNodeInfo& a);
void INET_API __doUnpacking(omnetpp::cCommBuffer *b, computeNodeInfo& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const computeNodeInfo& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, computeNodeInfo& obj) { __doUnpacking(b, obj); }

/**
 * Struct generated from inet/distributed_computing_power_network/message/cpn_message.msg:189 by opp_msgtool.
 */
struct INET_API routeInfo
{
    routeInfo();
    ::omnetpp::opp_string sidPath;
    ::omnetpp::simtime_t totalDelay = SIMTIME_ZERO;
    double reservedBandwidth = 0;
    ::omnetpp::simtime_t timestamp = SIMTIME_ZERO;
};

// helpers for local use
void INET_API __doPacking(omnetpp::cCommBuffer *b, const routeInfo& a);
void INET_API __doUnpacking(omnetpp::cCommBuffer *b, routeInfo& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const routeInfo& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, routeInfo& obj) { __doUnpacking(b, obj); }

/**
 * Struct generated from inet/distributed_computing_power_network/message/cpn_message.msg:196 by opp_msgtool.
 */
struct INET_API computeCandidateInfo
{
    computeCandidateInfo();
    computeNodeInfo nodeInfo;
    routeInfo pathInfo;
};

// helpers for local use
void INET_API __doPacking(omnetpp::cCommBuffer *b, const computeCandidateInfo& a);
void INET_API __doUnpacking(omnetpp::cCommBuffer *b, computeCandidateInfo& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const computeCandidateInfo& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, computeCandidateInfo& obj) { __doUnpacking(b, obj); }

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:201</tt> by opp_msgtool.
 * <pre>
 * class RespSummaryMsg extends inet::FieldsChunk
 * {
 *     // 通用字段
 *     int userId;           // 用户ID
 *     int taskId;           // 任务ID
 * 
 *     string msgType = "RespSummaryMsg";
 * 
 *     computeCandidateInfo candidateInfo[];
 * 
 *     chunkLength = B(12 + 32); // 在构造函数中直接赋值
 * }
 * 
 * // ==============================================
 * // ================== CGMP 协议 ==================
 * // ==============================================
 * </pre>
 */
class INET_API RespSummaryMsg : public ::inet::FieldsChunk
{
  protected:
    int userId = 0;
    int taskId = 0;
    ::omnetpp::opp_string msgType = "RespSummaryMsg";
    computeCandidateInfo *candidateInfo = nullptr;
    size_t candidateInfo_arraysize = 0;

  private:
    void copy(const RespSummaryMsg& other);

  protected:
    bool operator==(const RespSummaryMsg&) = delete;

  public:
    RespSummaryMsg();
    RespSummaryMsg(const RespSummaryMsg& other);
    virtual ~RespSummaryMsg();
    RespSummaryMsg& operator=(const RespSummaryMsg& other);
    virtual RespSummaryMsg *dup() const override {return new RespSummaryMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getUserId() const;
    virtual void setUserId(int userId);

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);

    virtual void setCandidateInfoArraySize(size_t size);
    virtual size_t getCandidateInfoArraySize() const;
    virtual const computeCandidateInfo& getCandidateInfo(size_t k) const;
    virtual computeCandidateInfo& getCandidateInfoForUpdate(size_t k) { handleChange();return const_cast<computeCandidateInfo&>(const_cast<RespSummaryMsg*>(this)->getCandidateInfo(k));}
    virtual void setCandidateInfo(size_t k, const computeCandidateInfo& candidateInfo);
    virtual void insertCandidateInfo(size_t k, const computeCandidateInfo& candidateInfo);
    [[deprecated]] void insertCandidateInfo(const computeCandidateInfo& candidateInfo) {appendCandidateInfo(candidateInfo);}
    virtual void appendCandidateInfo(const computeCandidateInfo& candidateInfo);
    virtual void eraseCandidateInfo(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RespSummaryMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RespSummaryMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:217</tt> by opp_msgtool.
 * <pre>
 * class CgmpQueryMsg extends inet::FieldsChunk
 * {
 *     string msgType = "CGMP_Query";
 *     simtime_t sendTime;          // 查询发送时间戳
 * 
 *     chunkLength = B(8); // 在构造函数中直接赋值
 * }
 * </pre>
 */
class INET_API CgmpQueryMsg : public ::inet::FieldsChunk
{
  protected:
    ::omnetpp::opp_string msgType = "CGMP_Query";
    ::omnetpp::simtime_t sendTime = SIMTIME_ZERO;

  private:
    void copy(const CgmpQueryMsg& other);

  protected:
    bool operator==(const CgmpQueryMsg&) = delete;

  public:
    CgmpQueryMsg();
    CgmpQueryMsg(const CgmpQueryMsg& other);
    virtual ~CgmpQueryMsg();
    CgmpQueryMsg& operator=(const CgmpQueryMsg& other);
    virtual CgmpQueryMsg *dup() const override {return new CgmpQueryMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);

    virtual ::omnetpp::simtime_t getSendTime() const;
    virtual void setSendTime(::omnetpp::simtime_t sendTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CgmpQueryMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CgmpQueryMsg& obj) {obj.parsimUnpack(b);}

/**
 * Struct generated from inet/distributed_computing_power_network/message/cpn_message.msg:224 by opp_msgtool.
 */
struct INET_API cgmpTaskState
{
    cgmpTaskState();
    int userId = 0;
    int taskId = 0;
    ::omnetpp::simtime_t remainingExecutionTime = SIMTIME_ZERO;
};

// helpers for local use
void INET_API __doPacking(omnetpp::cCommBuffer *b, const cgmpTaskState& a);
void INET_API __doUnpacking(omnetpp::cCommBuffer *b, cgmpTaskState& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const cgmpTaskState& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, cgmpTaskState& obj) { __doUnpacking(b, obj); }

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:230</tt> by opp_msgtool.
 * <pre>
 * class CgmpReportMsg extends inet::FieldsChunk
 * {
 *     string msgType = "CGMP_Report";
 * 
 *     int computeNodeId;
 *     int computeNodePort;          // 算力节点端口号
 *     int computingType; 			// 节点算力类型，0表示CPU，1表示GPU    
 *     L3Address computeNodeAddress; // 算力节点IP地址
 *     L3Address serviceGroupAddress; // 算力组地址
 *     double computingCapacity;	// 节点计算能力(FLOPs/s)
 *     double availableStorage;     // 可用存储(MB)
 *     double maxNetworkBandwidth;  // 可用网络带宽(Mbps)
 *     double computeCost;          // 节点使用单价(￥/s)
 *     simtime_t queueingTime;      // 节点等待队列预计排队时间
 *     cgmpTaskState taskState[];   // 节点当前任务剩余执行时间
 *     simtime_t querySendTime;     // 查询发送时间戳
 *     simtime_t sendTime;          // 时间戳
 * 
 *     chunkLength = B(12 + 72); // 在构造函数中直接赋值
 * }
 * 
 * 
 * // ==============================================
 * // ============ 任务完成通告消息 =================
 * // ==============================================
 * </pre>
 */
class INET_API CgmpReportMsg : public ::inet::FieldsChunk
{
  protected:
    ::omnetpp::opp_string msgType = "CGMP_Report";
    int computeNodeId = 0;
    int computeNodePort = 0;
    int computingType = 0;
    L3Address computeNodeAddress;
    L3Address serviceGroupAddress;
    double computingCapacity = 0;
    double availableStorage = 0;
    double maxNetworkBandwidth = 0;
    double computeCost = 0;
    ::omnetpp::simtime_t queueingTime = SIMTIME_ZERO;
    cgmpTaskState *taskState = nullptr;
    size_t taskState_arraysize = 0;
    ::omnetpp::simtime_t querySendTime = SIMTIME_ZERO;
    ::omnetpp::simtime_t sendTime = SIMTIME_ZERO;

  private:
    void copy(const CgmpReportMsg& other);

  protected:
    bool operator==(const CgmpReportMsg&) = delete;

  public:
    CgmpReportMsg();
    CgmpReportMsg(const CgmpReportMsg& other);
    virtual ~CgmpReportMsg();
    CgmpReportMsg& operator=(const CgmpReportMsg& other);
    virtual CgmpReportMsg *dup() const override {return new CgmpReportMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);

    virtual int getComputeNodeId() const;
    virtual void setComputeNodeId(int computeNodeId);

    virtual int getComputeNodePort() const;
    virtual void setComputeNodePort(int computeNodePort);

    virtual int getComputingType() const;
    virtual void setComputingType(int computingType);

    virtual const L3Address& getComputeNodeAddress() const;
    virtual L3Address& getComputeNodeAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<CgmpReportMsg*>(this)->getComputeNodeAddress());}
    virtual void setComputeNodeAddress(const L3Address& computeNodeAddress);

    virtual const L3Address& getServiceGroupAddress() const;
    virtual L3Address& getServiceGroupAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<CgmpReportMsg*>(this)->getServiceGroupAddress());}
    virtual void setServiceGroupAddress(const L3Address& serviceGroupAddress);

    virtual double getComputingCapacity() const;
    virtual void setComputingCapacity(double computingCapacity);

    virtual double getAvailableStorage() const;
    virtual void setAvailableStorage(double availableStorage);

    virtual double getMaxNetworkBandwidth() const;
    virtual void setMaxNetworkBandwidth(double maxNetworkBandwidth);

    virtual double getComputeCost() const;
    virtual void setComputeCost(double computeCost);

    virtual ::omnetpp::simtime_t getQueueingTime() const;
    virtual void setQueueingTime(::omnetpp::simtime_t queueingTime);

    virtual void setTaskStateArraySize(size_t size);
    virtual size_t getTaskStateArraySize() const;
    virtual const cgmpTaskState& getTaskState(size_t k) const;
    virtual cgmpTaskState& getTaskStateForUpdate(size_t k) { handleChange();return const_cast<cgmpTaskState&>(const_cast<CgmpReportMsg*>(this)->getTaskState(k));}
    virtual void setTaskState(size_t k, const cgmpTaskState& taskState);
    virtual void insertTaskState(size_t k, const cgmpTaskState& taskState);
    [[deprecated]] void insertTaskState(const cgmpTaskState& taskState) {appendTaskState(taskState);}
    virtual void appendTaskState(const cgmpTaskState& taskState);
    virtual void eraseTaskState(size_t k);

    virtual ::omnetpp::simtime_t getQuerySendTime() const;
    virtual void setQuerySendTime(::omnetpp::simtime_t querySendTime);

    virtual ::omnetpp::simtime_t getSendTime() const;
    virtual void setSendTime(::omnetpp::simtime_t sendTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CgmpReportMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CgmpReportMsg& obj) {obj.parsimUnpack(b);}

/**
 * Enum generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:255</tt> by opp_msgtool.
 * <pre>
 * enum TaskFailureCode
 * {
 *     TASK_OK = 0;
 *     TASK_INVALID_COMPUTING_TYPE = 1;
 *     TASK_INSUFFICIENT_STORAGE = 2;
 *     TASK_INSUFFICIENT_BANDWIDTH = 3;
 *     TASK_INVALID_RESOURCE_REQUEST = 4;
 * }
 * </pre>
 */
enum TaskFailureCode {
    TASK_OK = 0,
    TASK_INVALID_COMPUTING_TYPE = 1,
    TASK_INSUFFICIENT_STORAGE = 2,
    TASK_INSUFFICIENT_BANDWIDTH = 3,
    TASK_INVALID_RESOURCE_REQUEST = 4
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskFailureCode& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskFailureCode& e) { int n; b->unpack(n); e = static_cast<TaskFailureCode>(n); }

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/cpn_message.msg:263</tt> by opp_msgtool.
 * <pre>
 * class TaskCompletionMsg extends inet::FieldsChunk
 * {
 *     int userId;                       // 用户ID
 *     int taskId;                       // 任务ID
 *     L3Address computeNodeAddress;     // 算力节点地址
 *     int computeNodePort;              // 算力节点端口
 *     L3Address userNodeAddress;        // 用户节点地址
 *     simtime_t completionTime;         // 任务完成时间
 *     bool success;                     // 任务是否成功完成
 *     int failureCode = 0;              // 失败原因(TaskFailureCode)
 *     string failureReason;             // 失败原因文本
 *     double taskResult;                // 任务结果大小
 *     double executionTime;             // 实际执行耗时(sec)
 * 
 *     string msgType = "TASK_COMPLETION";
 *     chunkLength = B(64);
 * }
 * </pre>
 */
class INET_API TaskCompletionMsg : public ::inet::FieldsChunk
{
  protected:
    int userId = 0;
    int taskId = 0;
    L3Address computeNodeAddress;
    int computeNodePort = 0;
    L3Address userNodeAddress;
    ::omnetpp::simtime_t completionTime = SIMTIME_ZERO;
    bool success = false;
    int failureCode = 0;
    ::omnetpp::opp_string failureReason;
    double taskResult = 0;
    double executionTime = 0;
    ::omnetpp::opp_string msgType = "TASK_COMPLETION";

  private:
    void copy(const TaskCompletionMsg& other);

  protected:
    bool operator==(const TaskCompletionMsg&) = delete;

  public:
    TaskCompletionMsg();
    TaskCompletionMsg(const TaskCompletionMsg& other);
    virtual ~TaskCompletionMsg();
    TaskCompletionMsg& operator=(const TaskCompletionMsg& other);
    virtual TaskCompletionMsg *dup() const override {return new TaskCompletionMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getUserId() const;
    virtual void setUserId(int userId);

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual const L3Address& getComputeNodeAddress() const;
    virtual L3Address& getComputeNodeAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<TaskCompletionMsg*>(this)->getComputeNodeAddress());}
    virtual void setComputeNodeAddress(const L3Address& computeNodeAddress);

    virtual int getComputeNodePort() const;
    virtual void setComputeNodePort(int computeNodePort);

    virtual const L3Address& getUserNodeAddress() const;
    virtual L3Address& getUserNodeAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<TaskCompletionMsg*>(this)->getUserNodeAddress());}
    virtual void setUserNodeAddress(const L3Address& userNodeAddress);

    virtual ::omnetpp::simtime_t getCompletionTime() const;
    virtual void setCompletionTime(::omnetpp::simtime_t completionTime);

    virtual bool getSuccess() const;
    virtual void setSuccess(bool success);

    virtual int getFailureCode() const;
    virtual void setFailureCode(int failureCode);

    virtual const char * getFailureReason() const;
    virtual void setFailureReason(const char * failureReason);

    virtual double getTaskResult() const;
    virtual void setTaskResult(double taskResult);

    virtual double getExecutionTime() const;
    virtual void setExecutionTime(double executionTime);

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskCompletionMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskCompletionMsg& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::CprpRequestMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::CprpRequestMsg*>(ptr.get<cObject>()); }
template<> inline inet::CprpResponseMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::CprpResponseMsg*>(ptr.get<cObject>()); }
template<> inline inet::CprpConfirmMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::CprpConfirmMsg*>(ptr.get<cObject>()); }
template<> inline inet::CancelMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::CancelMsg*>(ptr.get<cObject>()); }
template<> inline inet::TaskRequestMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::TaskRequestMsg*>(ptr.get<cObject>()); }
template<> inline inet::TaskDataMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::TaskDataMsg*>(ptr.get<cObject>()); }
template<> inline inet::RespTimeoutSelfMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::RespTimeoutSelfMsg*>(ptr.get<cObject>()); }
inline any_ptr toAnyPtr(const inet::computeNodeInfo *p) {return any_ptr(p);}
template<> inline inet::computeNodeInfo *fromAnyPtr(any_ptr ptr) { return ptr.get<inet::computeNodeInfo>(); }
inline any_ptr toAnyPtr(const inet::routeInfo *p) {return any_ptr(p);}
template<> inline inet::routeInfo *fromAnyPtr(any_ptr ptr) { return ptr.get<inet::routeInfo>(); }
inline any_ptr toAnyPtr(const inet::computeCandidateInfo *p) {return any_ptr(p);}
template<> inline inet::computeCandidateInfo *fromAnyPtr(any_ptr ptr) { return ptr.get<inet::computeCandidateInfo>(); }
template<> inline inet::RespSummaryMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::RespSummaryMsg*>(ptr.get<cObject>()); }
template<> inline inet::CgmpQueryMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::CgmpQueryMsg*>(ptr.get<cObject>()); }
inline any_ptr toAnyPtr(const inet::cgmpTaskState *p) {return any_ptr(p);}
template<> inline inet::cgmpTaskState *fromAnyPtr(any_ptr ptr) { return ptr.get<inet::cgmpTaskState>(); }
template<> inline inet::CgmpReportMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::CgmpReportMsg*>(ptr.get<cObject>()); }
template<> inline inet::TaskCompletionMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::TaskCompletionMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_CPN_MESSAGE_M_H

