//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/distributed_computing_power_network/message/CpnPathHeader.msg.
//

#ifndef __INET_CPNPATHHEADER_M_H
#define __INET_CPNPATHHEADER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class CpnPathReq;
class CpnPathInd;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/TagBase_m.h" // import inet.common.TagBase

#include "inet/networklayer/common/L3Address_m.h" // import inet.networklayer.common.L3Address


namespace inet {

/**
 * Enum generated from <tt>inet/distributed_computing_power_network/message/CpnPathHeader.msg:8</tt> by opp_msgtool.
 * <pre>
 * // 路径操作模式
 * enum CpnPathMode
 * {
 *     PATH_RECORD_MODE = 0;   // 路径记录模式: 记录转发路径并进行带宽预留
 *     PATH_USE_MODE = 1;      // 路径使用模式: 按照SID列表进行源路由转发
 * }
 * </pre>
 */
enum CpnPathMode {
    PATH_RECORD_MODE = 0,
    PATH_USE_MODE = 1
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CpnPathMode& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CpnPathMode& e) { int n; b->unpack(n); e = static_cast<CpnPathMode>(n); }

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/CpnPathHeader.msg:16</tt> by opp_msgtool.
 * <pre>
 * // 算力网络路径记录请求Tag (应用层 -> 网络层)
 * // 用于请求网络层记录路径或使用指定路径转发
 * class CpnPathReq extends TagBase
 * {
 *     int mode = 0;                    // 路径操作模式: PATH_RECORD_MODE 或 PATH_USE_MODE
 * 
 *     // 流标识
 *     int userId = -1;                 // 用户ID
 *     int taskId = -1;                 // 任务ID
 * 
 *     // 路径记录模式字段
 *     L3Address hopAddress[];          // 记录的跳地址列表(网络层填充)
 *     L3Address userGatewayAddress;    // 用户网关地址(用于带宽预留标识)
 *     double requiredBandwidth = 0;    // 所需带宽(用于预留)
 * 
 *     // 路径使用模式字段
 *     L3Address sidList[];             // SID路径列表(源路由)
 *     int currentHopIndex = 0;         // 当前跳索引
 * }
 * </pre>
 */
class INET_API CpnPathReq : public ::inet::TagBase
{
  protected:
    int mode = 0;
    int userId = -1;
    int taskId = -1;
    L3Address *hopAddress = nullptr;
    size_t hopAddress_arraysize = 0;
    L3Address userGatewayAddress;
    double requiredBandwidth = 0;
    L3Address *sidList = nullptr;
    size_t sidList_arraysize = 0;
    int currentHopIndex = 0;

  private:
    void copy(const CpnPathReq& other);

  protected:
    bool operator==(const CpnPathReq&) = delete;

  public:
    CpnPathReq();
    CpnPathReq(const CpnPathReq& other);
    virtual ~CpnPathReq();
    CpnPathReq& operator=(const CpnPathReq& other);
    virtual CpnPathReq *dup() const override {return new CpnPathReq(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getMode() const;
    virtual void setMode(int mode);

    virtual int getUserId() const;
    virtual void setUserId(int userId);

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual void setHopAddressArraySize(size_t size);
    virtual size_t getHopAddressArraySize() const;
    virtual const L3Address& getHopAddress(size_t k) const;
    virtual L3Address& getHopAddressForUpdate(size_t k) { return const_cast<L3Address&>(const_cast<CpnPathReq*>(this)->getHopAddress(k));}
    virtual void setHopAddress(size_t k, const L3Address& hopAddress);
    virtual void insertHopAddress(size_t k, const L3Address& hopAddress);
    [[deprecated]] void insertHopAddress(const L3Address& hopAddress) {appendHopAddress(hopAddress);}
    virtual void appendHopAddress(const L3Address& hopAddress);
    virtual void eraseHopAddress(size_t k);

    virtual const L3Address& getUserGatewayAddress() const;
    virtual L3Address& getUserGatewayAddressForUpdate() { return const_cast<L3Address&>(const_cast<CpnPathReq*>(this)->getUserGatewayAddress());}
    virtual void setUserGatewayAddress(const L3Address& userGatewayAddress);

    virtual double getRequiredBandwidth() const;
    virtual void setRequiredBandwidth(double requiredBandwidth);

    virtual void setSidListArraySize(size_t size);
    virtual size_t getSidListArraySize() const;
    virtual const L3Address& getSidList(size_t k) const;
    virtual L3Address& getSidListForUpdate(size_t k) { return const_cast<L3Address&>(const_cast<CpnPathReq*>(this)->getSidList(k));}
    virtual void setSidList(size_t k, const L3Address& sidList);
    virtual void insertSidList(size_t k, const L3Address& sidList);
    [[deprecated]] void insertSidList(const L3Address& sidList) {appendSidList(sidList);}
    virtual void appendSidList(const L3Address& sidList);
    virtual void eraseSidList(size_t k);

    virtual int getCurrentHopIndex() const;
    virtual void setCurrentHopIndex(int currentHopIndex);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CpnPathReq& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CpnPathReq& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/distributed_computing_power_network/message/CpnPathHeader.msg:36</tt> by opp_msgtool.
 * <pre>
 * // 算力网络路径记录指示Tag (网络层 -> 应用层)
 * // 用于向应用层传递已记录的路径信息
 * class CpnPathInd extends TagBase
 * {
 *     int userId = -1;                 // 用户ID
 *     int taskId = -1;                 // 任务ID
 * 
 *     L3Address hopAddress[];          // 记录的跳地址列表
 *     int hopCount = 0;                // 跳数
 *     double reservedBandwidth = 0;    // 已预留带宽
 * }
 * </pre>
 */
class INET_API CpnPathInd : public ::inet::TagBase
{
  protected:
    int userId = -1;
    int taskId = -1;
    L3Address *hopAddress = nullptr;
    size_t hopAddress_arraysize = 0;
    int hopCount = 0;
    double reservedBandwidth = 0;

  private:
    void copy(const CpnPathInd& other);

  protected:
    bool operator==(const CpnPathInd&) = delete;

  public:
    CpnPathInd();
    CpnPathInd(const CpnPathInd& other);
    virtual ~CpnPathInd();
    CpnPathInd& operator=(const CpnPathInd& other);
    virtual CpnPathInd *dup() const override {return new CpnPathInd(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getUserId() const;
    virtual void setUserId(int userId);

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual void setHopAddressArraySize(size_t size);
    virtual size_t getHopAddressArraySize() const;
    virtual const L3Address& getHopAddress(size_t k) const;
    virtual L3Address& getHopAddressForUpdate(size_t k) { return const_cast<L3Address&>(const_cast<CpnPathInd*>(this)->getHopAddress(k));}
    virtual void setHopAddress(size_t k, const L3Address& hopAddress);
    virtual void insertHopAddress(size_t k, const L3Address& hopAddress);
    [[deprecated]] void insertHopAddress(const L3Address& hopAddress) {appendHopAddress(hopAddress);}
    virtual void appendHopAddress(const L3Address& hopAddress);
    virtual void eraseHopAddress(size_t k);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);

    virtual double getReservedBandwidth() const;
    virtual void setReservedBandwidth(double reservedBandwidth);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CpnPathInd& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CpnPathInd& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::CpnPathReq *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::CpnPathReq*>(ptr.get<cObject>()); }
template<> inline inet::CpnPathInd *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::CpnPathInd*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_CPNPATHHEADER_M_H

